### ISSUE TITLE
Selenium Webdriver - DeprecationWarning

### ISSUE THREAD

**Issue by lugezz** [joaduo/xpathwebdriver#2]
### Selenium Webdriver - DeprecationWarning

Please consider this deprecation warning

`env/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py:388: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.1.0. Instead use HTTResponse.headers.get(name, default).`

**Comment by joaduo** [comment]
@lugezz 
`site-packages/selenium/webdriver/remote/remote_connection.py:388`
That warning is related to the selenium package and not directly implemented inside xpathwebdriver.
Nevertheless you can try upgrading `pip install selenium --upgrade` and see if that fixes the problem.
If it fixes it, then let me know in this issue what version of selenium does the trick.

**Comment by lugezz** [comment]
@joaduo this solved the problem, I updated **Selelium** from **4.5.0** to **4.7.2** and it's working now, I thought it was a implemented by xpathwebdriver but it wasn't. Thank you!!
